apiVersion: apps/v1
kind: Deployment
metadata:
  name: typing-game-deployment
  labels:
    app: typing-game
spec:
  selector:
    matchLabels:
      app: typing-game
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: typing-game
    spec:
      containers:
      - name: typing-game
        image: localhost:32000/minelminel/typing-game:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80