apiVersion: v1
kind: Service
metadata:
    name: typing-game-external
spec:
    selector:
        app: typing-game
    type: NodePort
    ports:
        - protocol: TCP
          # inside the cluster, what port does the service expose?
          port: 80
          # which port do pods selected by this service expose?
          targetPort: 80